### PR TITLE
Fix errors when compiling under Purescript 0.8.3

### PR DESCRIPTION
**Pull request by rgrempel**
This pull request would fix all of the errors which otherwise occur when compiling & testing under Purescript 0.8.3.

In addition to removing the orphan instance mentioned in #1, I have also updated the tests to avoid orphan instances. (Essentially, we now test a `newtype` that wraps `Zipper`, so we can create an `Arbitrary` instance for the `newtype` without it being an orphan).

I've also bumped the version, and remove the dependency on purescript-functor-compose, since it was only used by the removed instance. Finally, I used a more recent version of purescript-quickcheck in bower.json -- the older version was causing some problems, though I can't remember exactly what they were.

I haven't fixed all the warnings which are emitted by Purescript 0.8.3 -- I could do that in a separate PR if you like.

### CODE REVIEW

**Comment by DavidHarrison** [comment]
Looks great! Thank you!

**Comment by DavidHarrison** [comment]
I'll fix the remaining errors; I need to get back up to speed with the latest release of PureScript. Thanks again!

**Comment by rgrempel** [comment]
BTW, I just noticed that @parsonsmatt has a nice fix for the original orphan instance problem here:

https://github.com/parsonsmatt/purescript-list-zipper/commit/58a5d96d644a0c14fee815cfd1df58ac19f30377

... that is, even nicer than removing it :-)

Not sure why I didn't think of that!

**Comment by parsonsmatt** [comment]
It seems somewhat out of place, if that's the only time `Compose` is used. Since we have to newtype it anyway, it might be better for it to live in it's own module, and have more instances fleshed out.

**Pull request merged**
